parameters:
    logger.key: command
    currency.default: EUR
services:
    logger:
        class:     Monolog\Logger
        arguments: ['%logger.key%']
    currencyService:
        class:     CodingExercise\Service\CurrencyService
        arguments:
            - '%currency.default%'
            - EUR:
               USD: 1.21
               GBP: 1.21
    ruleNoDiscount:
        class:     CodingExercise\Model\Discount\Rule\NoDiscount
    ruleXOrdersPerMonth:
        class:     CodingExercise\Model\Discount\Rule\XOrdersPerMonth
        arguments: [3,10]
    ruleLastMonthTotal:
        class:     CodingExercise\Model\Discount\Rule\LastMonthTotal
        arguments: [1000,5,'@currencyService']
    aggregator:
        class:     CodingExercise\Model\Discount\Aggregator\CustomerMaxAmount
    discountService:
         class:    CodingExercise\Service\DiscountService
         arguments:
             - [ '@ruleNoDiscount', '@ruleXOrdersPerMonth', '@ruleLastMonthTotal' ]
             - '@aggregator'
         calls:
            - [setLogger, ['@logger']]
    storage:
         class:     CodingExercise\Storage\CsvStorage
         arguments: ['@currencyService']
         calls:
            - [setLogger, ['@logger']]
    invoiceService:
         class:     CodingExercise\Service\InvoiceService
         arguments:
             - '@storage'
             - '@currencyService'
             - '@discountService'
