parameters:
    logger.key: command
    currency.default: EUR
    rules:
        ruleXOrdersPerMonth:
            x: 3
            percent: 10
services:
    logger:
        class:     Monolog\Logger
        arguments: ['%logger.key%']
    currencyFactory:
        class:     CodingExercise\Model\Currency\CurrencyFactory
        arguments:
            - '%currency.default%'
            - EUR:
               USD: 1.21
               GBP: 1.21
    ruleNoDiscount:
        class:     CodingExercise\Model\Discount\Rule\NoDiscount
    ruleXOrdersPerMonth:
        class:     CodingExercise\Model\Discount\Rule\XOrdersPerMonth
        arguments: [3,10]
    ruleLastMonthTotal:
        class:     CodingExercise\Model\Discount\Rule\LastMonthTotal
        arguments: [1000,5,'@currencyFactory']
    aggregator:
        class:     CodingExercise\Model\Discount\Aggregator\CustomerMaxAmount
    discountService:
         class:    CodingExercise\Service\DiscountService
         arguments:
             - [ '@ruleNoDiscount' ]
             - '@aggregator'
         calls:
            - [setLogger, ['@logger']]
    storage:
         class:     CodingExercise\Storage\CsvStorage
         arguments: ['@currencyFactory']
         calls:
            - [setLogger, ['@logger']]
    invoiceService:
         class:     CodingExercise\Service\InvoiceService
         arguments:
             - '@storage'
             - '@currencyFactory'
             - '@discountService'
